### ISSUE TITLE
internal error 500

### ISSUE THREAD

**Issue by ashrafalzyoud** [HugoHasenbein/redmine_more_previews#1]
`Completed 500 Internal Server Error in 1015ms (ActiveRecord: 284.0ms)
  
ActionView::Template::Error (undefined method `each' for nil:NilClass):
    1: <style>
    2: <% RedmineMorePreviews::Converter.active_mime_types.each do |ext, values| %>
    3: <% if s = values['icon'] %>
    4: <% converter = RedmineMorePreviews::Converter.find values['converter'] %>
    5: <% mime = values['mime'] %>
  
plugins/redmine_more_previews/app/views/hooks/redmine_more_previews/_icon_css.html.erb:2:in `_8a238ee1dae347173f06a0838df2b56c'
lib/redmine/hook/view_listener.rb:61:in `block (2 levels) in render_on'
lib/redmine/hook/view_listener.rb:59:in `map'
lib/redmine/hook/view_listener.rb:59:in `block in render_on'
lib/redmine/hook.rb:63:in `block (2 levels) in call_hook'
lib/redmine/hook.rb:63:in `each'
lib/redmine/hook.rb:63:in `block in call_hook'
lib/redmine/hook.rb:60:in `tap'
lib/redmine/hook.rb:60:in `call_hook'
lib/redmine/hook.rb:98:in `call_hook'
app/views/layouts/base.html.erb:16:in `_5eb19117b383473db2da7186fc7e76f4'`

**Comment by HugoHasenbein** [comment]
Dear Ashraf,

should now be fixed. Just download last version.

Best regards

Stephan
