### ISSUE TITLE
NoMethodError (undefined method `keys' for nil:NilClass)

### ISSUE THREAD

**Issue by STroyniak** [HugoHasenbein/redmine_more_previews#10]
Redmine Appliance Turnkey
Environment:
  Redmine version                4.0.3.stable
  Ruby version                   2.3.5-p376 (2017-09-14) [x86_64-linux]
  Rails version                  5.2.2.1
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.9.5
  Git                            2.11.0
  Filesystem                     
Redmine plugins:

Plugin installed as described. LibreOffice and pandoc installed.

When I try to preview pdf attachment I got internal server error and in production.log:

Started GET "/attachments/52" for 10.0.11.33 at 2021-02-26 21:55:01 +0100
Processing by AttachmentsController#show as HTML
  Parameters: {"id"=>"52"}
  Current user: username (id=6)
Completed 500 Internal Server Error in 16ms (ActiveRecord: 5.8ms)

**NoMethodError (undefined method `keys' for nil:NilClass):**

plugins/redmine_more_previews-main/lib/redmine_more_previews/lib/converter.rb:388:in `extensions_of'
plugins/redmine_more_previews-main/lib/redmine_more_previews/lib/converter.rb:384:in `active_extensions'
plugins/redmine_more_previews-main/lib/redmine_more_previews/lib/converter.rb:292:in `convertible?'
plugins/redmine_more_previews-main/lib/redmine_more_previews/patches/attachment_patch.rb:65:in `preview_convertible?'
plugins/redmine_more_previews-main/lib/redmine_more_previews/patches/attachments_controller_patch.rb:142:in `show_with_more_previews'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'

What is wrong ?

**Comment by HugoHasenbein** [comment]
Dear S. Troyniak,

I am not sure. Does it help, if you go to Administration-> Plugins-> Redmine More Previews and you choose, which file types should be converted?

If it helps, I may have a remedy, which wool go into the next version

**Comment by STroyniak** [comment]
A little progress: 
instead of unzipping .zip archive I did "git clone https://github.com/HugoHasenbein/redmine_more_previews.git".

Now I see in admin section:

Redmine plugins:
  redmine_more_previews          2.0.0
while od redmine.org there is 2.0.1 mention.

Besides during preview generating in production log:

Started GET "/attachments/more_preview/51/index.pdf" for 10.0.11.33 at 2021-02-27 14:00:59 +0100
Processing by AttachmentsController#more_preview as PDF
  Parameters: {"id"=>"51"}
  Current user: username (id=6)
**An error occured while generating preview for /var/www/redmine/files/2021/02/210225162459_e5f83d85899459ea8a87c77fed79e1ea.pdf
Exception was: undefined method `children' for Dir:Class**
/var/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/lib/conversion.rb:205:in `copy_over'
/var/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/lib/conversion.rb:188:in `block in cached_preview'
/usr/local/rbenv/versions/2.3.5/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/var/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/lib/conversion.rb:185:in `cached_preview'
/var/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/lib/conversion.rb:154:in `block in preview'
/var/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/lib/conversion.rb:119:in `synchronize'
/var/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/lib/conversion.rb:119:in `sync'
/var/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/lib/conversion.rb:154:in `preview'
/var/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/lib/converter.rb:336:in `convert'
/var/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachment_patch.rb:40:in `more_preview'
/var/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachments_controller_patch.rb:95:in `send_more_preview'
/var/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachments_controller_patch.rb:66:in `block (2 levels) in more_preview'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/action_controller/metal/mime_responds.rb:203:in `respond_to'
/var/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachments_controller_patch.rb:62:in `more_preview'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/abstract_controller/base.rb:194:in `process_action'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/var/www/redmine/lib/redmine/sudo_mode.rb:63:in `sudo_mode'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:136:in `run_callbacks'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.2.2.1/lib/active_support/notifications.rb:168:in `block in instrument'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.2.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.2.2.1/lib/active_support/notifications.rb:168:in `instrument'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activerecord-5.2.2.1/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/abstract_controller/base.rb:134:in `process'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionview-5.2.2.1/lib/action_view/rendering.rb:32:in `process'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/action_controller/metal.rb:191:in `dispatch'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/action_controller/metal.rb:252:in `dispatch'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/action_dispatch/routing/route_set.rb:34:in `serve'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/action_dispatch/journey/router.rb:52:in `block in serve'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/action_dispatch/journey/router.rb:35:in `each'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/action_dispatch/journey/router.rb:35:in `serve'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/action_dispatch/routing/route_set.rb:840:in `call'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rack-2.0.7/lib/rack/tempfile_reaper.rb:15:in `call'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rack-2.0.7/lib/rack/etag.rb:25:in `call'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rack-2.0.7/lib/rack/conditional_get.rb:25:in `call'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:232:in `context'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:226:in `call'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/cookies.rb:670:in `call'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-5.2.2.1/lib/rails/rack/logger.rb:38:in `call_app'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-5.2.2.1/lib/rails/rack/logger.rb:26:in `block in call'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:28:in `tagged'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:71:in `tagged'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-5.2.2.1/lib/rails/rack/logger.rb:26:in `call'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.2.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/static.rb:127:in `call'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rack-2.0.7/lib/rack/content_length.rb:15:in `call'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-5.2.2.1/lib/rails/engine.rb:524:in `call'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
  Rendering text template
  Rendered text template (0.0ms)
Sent data index.pdf (0.7ms)
Completed 200 OK in 19ms (Views: 0.6ms | ActiveRecord: 2.4ms)

despite I try preview .doc / .docx / .pdf file.

Plugin lightbox2 works ok during pdf preview.

**Comment by STroyniak** [comment]
Error:
Exception was: undefined method children' for Dir:Class** /var/www/redmine/plugins/redmine_more_previews
is caused because of too low version of Ruby. Min. v2.4 is required.
Checked with v2.6.6 - it works like a charm.

**Comment by STroyniak** [comment]
Please update you installation guide of that information. And instead of "download plugin and copy plugin folder redmine_more_previews go to Redmine's plugins folder" I suggest "git clone https://github.com/HugoHasenbein/redmine_more_previews.git".

**Comment by Truth1984** [comment]
same issue
```
redmine_1  | Completed 500 Internal Server Error in 26ms (ActiveRecord: 13.8ms)
redmine_1  |   
redmine_1  | NoMethodError (undefined method `keys' for nil:NilClass):
redmine_1  |   
redmine_1  | plugins/redmine_more_previews/lib/redmine_more_previews/lib/converter.rb:388:in `extensions_of'
redmine_1  | plugins/redmine_more_previews/lib/redmine_more_previews/lib/converter.rb:384:in `active_extensions'
redmine_1  | plugins/redmine_more_previews/lib/redmine_more_previews/lib/converter.rb:292:in `convertible?'
redmine_1  | lib/redmine/sudo_mode.rb:65:in `sudo_mode'
```

with ruby ` v2.6.6` (I'm using docker version btw)

**Comment by HugoHasenbein** [comment]
Dear Awada,

I added a fix. The issue should be solved.
