### ISSUE TITLE
Preview not working

### ISSUE THREAD

**Issue by Arean82** [HugoHasenbein/redmine_more_previews#100]
I have installed the plugin. I am using Redmine 5.1.3.stable. 
no issues during installation. 
After installation in Redmine I went to Administration -> Plugins -> Redmine More Previews and selected all options 

Then restarted apache
Now I selected an existing issue that has docx file , The problem here is the docx file is not previewing. It is giving me the default option to download

**Comment by HugoHasenbein** [comment]
and then the plugin needs to be activated for the project under Project -> Configuration

**Comment by Arean82** [comment]
Can you share the screenshot, please?
I am not able to locate the mentioned menu
![Screenshot 2024-10-01 162938](https://github.com/user-attachments/assets/73b5749d-0bd7-4f59-a8a7-04311b6fe19f)

**Comment by Arean82** [comment]
I found it , Thanks

**Comment by winters93** [comment]
Thanks to both of you! I strugeled at the same problem. I read the Readme 3 times...  Maybe you could add it somewhere?
