### ISSUE TITLE
Translation Files sparsed trought code

### ISSUE THREAD

**Issue by martinbra** [HugoHasenbein/redmine_more_previews#12]
Amazing Work @HugoHasenbein .
I noticed that there are some translation files in folder `redmine_more_previews/app/views/settings/redmine_more_previews/welcome/`
Could we move those texts to the `redmine_more_previews/config/locales/` files? 
This way it would be easier to point users to improve translations, since it would all be in one single file for each language.
What do you think? 
If you are ok with this, I will fork and make a PR (with some PT-BR improvements).

**Comment by HugoHasenbein** [comment]
In principle, yes - but in which way would do you want to include these files in a view? as yaml and l(:text...) ?

**Comment by martinbra** [comment]
Well, i'm new to ruby and haven't looked too much at the code yet, my intention was to use the welcome text as a string, just as the strings in the locales files... I'll have a try and report later.
