### ISSUE TITLE
Preview fails to display large spreadsheet (.xlsx) files

### ISSUE THREAD

**Issue by GaryAitken** [HugoHasenbein/redmine_more_previews#16]
If a .xlsx file is larger than ~1MB the preview only shows the file name, submitter, and date. 
Clicking the download link displays the whole file in libreoffice properly.
Tried with three files, 842 KB, 1.19 MB, 1.34 MB; all failed.
758 KB file displays fine.

**Comment by HugoHasenbein** [comment]
Dear Gary,

seems, there are far many different environments out there, than I originally expected. Try to activate caching in the plugin setting. If that remedies the situation, then I might have an idea where to tackle the issue.

**Comment by GaryAitken** [comment]
Cacheing solved this particular issue.
I have another one and one for Redmine_All_Thumbnails but will report them separately.
