### ISSUE TITLE
zippy prevents display of .docx of type "Microsoft Word 2007+"

### ISSUE THREAD

**Issue by GaryAitken** [HugoHasenbein/redmine_more_previews#17]
We have a smallish (284KB) file with extension .docx, for which "file <filename>" reports:
"Microsoft Word 2007+"
The issue displays with a zip icon, and if the zippy option is checked the file does not display.  If the zippy icon is unchecked, the icon is still the zip icon, but the file then displays ok.
The file has an embedded image and a table.
I may not be able to provide the file, unfortunately; have to check and maybe do some substitutions.

**Comment by HugoHasenbein** [comment]
Daer Gary,

I had an opportunity to reproduce the error with another xlsx file, which shows the same behavior. It seems, your xlsx file is either malformed or it is in a format, which is not recognized by Rails MimeMagick, which is used in redmine_more_preview. In fact, an xlsx file is a .zip compressed folder, but it has some deviations.

Try to open the xlsx file with Excel and save it to another file. Then upload this other file. It should be shown as an excel file with all_thumbnails and it should render fine.

I was downloading the malformed file from the global brands database: https://www.wipo.int/branddb/en/ <https://www.wipo.int/branddb/en/> this excel file is large, has many images and shows this peculiar behavior.

**Comment by HugoHasenbein** [comment]
The second issue about the images: it seems LibreOffice assigns random names for excel images on each conversion. That means, conversion of excel files with images will only work with cache turned on.
