### ISSUE TITLE
internal error

### ISSUE THREAD

**Issue by ashrafalzyoud** [HugoHasenbein/redmine_more_previews#2]
``
Processing by AttachmentsController#show as HTML
  Parameters: {"id"=>"3127", "filename"=>"قرار المواد الاولية اخشاب .pdf"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 53ms (ActiveRecord: 16.2ms)
  
NoMethodError (undefined method `keys' for nil:NilClass):
  
plugins/redmine_more_previews/lib/redmine_more_previews/lib/converter.rb:388:in `extensions_of'
plugins/redmine_more_previews/lib/redmine_more_previews/lib/converter.rb:384:in `active_extensions'
plugins/redmine_more_previews/lib/redmine_more_previews/lib/converter.rb:292:in `convertible?'
plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachment_patch.rb:65:in `preview_convertible?'
plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachments_controller_patch.rb:142:in `show_with_more_previews'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
``

**Comment by HugoHasenbein** [comment]
Dear Ashraf,

I need tuo understand, what ist going on. The plugin says, Pandoc is not installed, but it is not needed for viewing a pdf-file. So that is OK.

Please, can you list your other plugins, version of redmine, you are running and the environment, namely the operating system?

Is it Windows, Linux, Mac? Redmine 3.x or 4.x?

Currently, it seems, the plugin misses some files.

best regards

Stephan

**Comment by ashrafalzyoud** [comment]
redmine 4.1
ubuntu 20.04

``
 computed_custom_field          1.0.7
  redmine_agile                  1.5.4
  redmine_all_thumbnails         1.0.5
  redmine_checklists             3.1.18
  redmine_ckeditor               1.2.3
  redmine_cms                    1.2.1
  redmine_contacts               4.3.2
  redmine_contacts_helpdesk      4.1.10
  redmine_contacts_invoices      4.2.3
  redmine_custom_workflows       1.0.3
  redmine_default_custom_query   1.5.0
  redmine_drawio                 0.9.7
  redmine_drive                  1.0.1
  redmine_favorite_projects      2.1.1
  redmine_finance                2.1.7
  redmine_hide_sidebar           4.0.0
  redmine_issue_badge            0.1.4
  redmine_issue_view_columns     1.0.1
  redmine_lightbox2              0.5.1
  redmine_people                 1.5.2
  redmine_pivot_table            0.0.7
  redmine_preview_inline         1.0.3
  redmine_products               2.1.2
  redmine_questions              1.0.2
  redmine_reporter               1.0.3
  redmine_subtask_list_enhanced  1.1.1
  redmine_subtasks_inherited_fields 1.1.1
  redmine_tint_issues            1.1.0
  redmine_xlsx_format_issue_exporter 0.1.6
  redmine_zenedit                1.0.3
  view_customize                 2.7.0
``

**Comment by HugoHasenbein** [comment]
Did you configure the plugin? Administration->Plugins->RedmineMorePreviews-> select any extension and save.
Not configuring should not cause the problems, but just to make sure.

**Comment by ashrafalzyoud** [comment]
its work now
but the preview in small size not in full page
![333](https://user-images.githubusercontent.com/50211455/99225657-1356f680-27f1-11eb-9b8d-16dae3381987.png)

**Comment by ashrafalzyoud** [comment]
its work now
but the preview in small size not in full page
![33333](https://user-images.githubusercontent.com/50211455/99225738-35e90f80-27f1-11eb-8805-e9102f650123.png)

**Comment by HugoHasenbein** [comment]
Dear Ashraf,

what did you change to make it work?
The preview size is set after the page has been loaded, using javascript. Are you using InternetExplorer?

**Comment by ashrafalzyoud** [comment]
configure the plugin? Administration->Plugins->RedmineMorePreviews-> select any extension and save
im do configure
im using the google chorme
the problem now the preview size

**Comment by HugoHasenbein** [comment]
I'll try to reproduce your error - please hold on

**Comment by ashrafalzyoud** [comment]
in firefox work PERFECT
but in google chorme (NO)
THX FOR U

**Comment by HugoHasenbein** [comment]
I'll look over waht is different in Chrome

**Comment by HugoHasenbein** [comment]
Dear Ashraf,

the Chrome Issue should be fixed by now
