### ISSUE TITLE
Bitnami Redmine-4.2.1 error

### ISSUE THREAD

**Issue by Kolenmi** [HugoHasenbein/redmine_more_previews#20]
After installing the plugin, I get the following message...
(in /opt/bitnami/apps/redmine/htdocs)
rake aborted!
LoadError: cannot load such file -- mimemagic/overlay
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_more_previews/lib/redmine_more_previews/patches/repository_patch.rb:24:in `<top (require                    d)>'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_more_previews/lib/redmine_more_previews.rb:31:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_more_previews/init.rb:69:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:187:in `block in load'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:178:in `each'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:178:in `load'
/opt/bitnami/apps/redmine/htdocs/config/initializers/30-redmine.rb:20:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/config/environment.rb:16:in `<top (required)>'
/opt/bitnami/ruby/bin/bundle:23:in `load'
/opt/bitnami/ruby/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)

Please, can You resovle this issue
Thank You

**Comment by HugoHasenbein** [comment]
did you do a `bundle install`?

**Comment by Kolenmi** [comment]
Yes, I'm.

**Comment by HugoHasenbein** [comment]
there are many posts about mimemagic having an iisue

maybe this info helps

https://stackoverflow.com/questions/66837647/heroku-loaderror-cannot-load-such-file-mimemagic-overlay

**Comment by paulbutenko** [comment]
there are couple of issues for version 4.2.1

1. mimemagic
   [here ](https://dev.to/cseeman/what-s-up-with-mimemagic-breaking-everything-he1) is great description of what is going on with it.
   I have used 
     `gem "mimemagic", "~> 0.3.7"`
   in `redmine_more_previews/Gemfile` and it helped

2. rubyzip
    current version of  `redmine_more_previews/converters/zippy/Gemfile` has `rubyzip` which interferes with `Gemfile` from redmine. Removing it from zippy should help.

**Comment by iprok** [comment]
I confirm the problem with official redmine image from https://hub.docker.com/_/redmine/. Redmine version 4.1.3.

Fix with 
`gem "mimemagic", "~> 0.3.7"`
works for me
