### ISSUE TITLE
windows installation failed

### ISSUE THREAD

**Issue by Cloud-zack** [HugoHasenbein/redmine_more_previews#21]
bitnami redmine 4.2  install execute ‘bundle install’  error log：
Your Gemfile lists the gem redmine_crm (>= 0) more than once.
You should probably keep only one of them.
Remove any duplicate entries and specify the gem only once.
While it's not a problem now, it could cause errors if you change the version of one of them later.

[!] There was an error parsing `Gemfile`:
[!] There was an error parsing `Gemfile`:
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: rubyzip (~> 2.3.0) and rubyzip (>= 0). Bundler cannot continue.

 #  from D:/Redmine/apps/redmine/htdocs/plugins/redmine_more_previews/converters/zippy/Gemfile:1
 #  -------------------------------------------
 #  gem 'rubyzip'
 >  gem 'zlib' #  gem 'rubyzip'
 #  -------------------------------------------
. Bundler cannot continue.

 #  from D:/Redmine/apps/redmine/htdocs/plugins/redmine_more_previews/Gemfile:3
 #  -------------------------------------------
 #
 >  gem 'mimemagic'
 #  # Load plugins' Gemfiles
 #  -------------------------------------------
. Bundler cannot continue.

 #  from D:/Redmine/apps/redmine/htdocs/Gemfile:110
 #  -------------------------------------------
 #    eval_gemfile file
 >  end
 #  source 'https://rubygems.org'
 #  -------------------------------------------

D:\Redmine\apps\redmine\htdocs>bundle install
Your Gemfile lists the gem redmine_crm (>= 0) more than once.
You should probably keep only one of them.
Remove any duplicate entries and specify the gem only once.
While it's not a problem now, it could cause errors if you change the version of one of them later.
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 13.0.3
Using concurrent-ruby 1.1.8
Using i18n 1.8.10
Using minitest 5.14.4
Using thread_safe 0.3.6
Using tzinfo 1.2.9
Using activesupport 5.2.5
Using builder 3.2.4
Using erubi 1.10.0
Using racc 1.5.2 (x64-mingw32)
Using nokogiri 1.11.2 (x64-mingw32)
Using rails-dom-testing 2.0.3
Using crass 1.0.6
Using loofah 2.9.0
Using rails-html-sanitizer 1.3.0
Using actionview 5.2.5
Using rack 2.2.3
Using rack-test 1.1.0
Using actionpack 5.2.5
Using nio4r 2.5.7 (x64-mingw32)
Using websocket-extensions 0.1.5
Using websocket-driver 0.7.3 (x64-mingw32)
Using actioncable 5.2.5
Using globalid 0.4.2
Using activejob 5.2.5
Using mini_mime 1.0.3
Using mail 2.7.1
Using actionmailer 5.2.5
Using method_source 1.0.0
Using thor 1.1.0
Using railties 5.2.5
Using actionpack-xml_parser 2.0.1
Using activemodel 5.2.5
Using arel 9.0.0
Using activerecord 5.2.5
Using activerecord-compatible_legacy_migration 0.1.1
Using marcel 1.0.0
Using activestorage 5.2.5
Using public_suffix 4.0.6
Using addressable 2.7.0
Using awesome_nested_set 3.4.0
Using bundler 2.1.2
Using chunky_png 1.4.0
Using css_parser 1.9.0
Using csv 3.1.9
Using daemons 1.3.1
Using eventmachine 1.2.7 (x64-mingw32)
Using htmlentities 4.3.4
Using jbuilder 2.11.2
Using liquid 2.6.3
Fetching mimemagic 0.4.3
Installing mimemagic 0.4.3 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
D:/Redmine/ruby/lib/ruby/gems/2.6.0/gems/mimemagic-0.4.3/ext/mimemagic
D:/Redmine/ruby/bin/ruby.exe -rrubygems
D:/Redmine/ruby/lib/ruby/gems/2.6.0/gems/rake-13.0.3/exe/rake
RUBYARCHDIR\=D:/Redmine/ruby/lib/ruby/gems/2.6.0/extensions/x64-mingw32/2.6.0/mimemagic-0.4.3
RUBYLIBDIR\=D:/Redmine/ruby/lib/ruby/gems/2.6.0/extensions/x64-mingw32/2.6.0/mimemagic-0.4.3
rake aborted!
Could not find MIME type database in the following locations:
["/usr/local/share/mime/packages/freedesktop.org.xml",
"/opt/homebrew/share/mime/packages/freedesktop.org.xml",
"/opt/local/share/mime/packages/freedesktop.org.xml",
"/usr/share/mime/packages/freedesktop.org.xml"]

Ensure you have either installed the shared-mime-info package for your
distribution, or
obtain a version of freedesktop.org.xml and set FREEDESKTOP_MIME_TYPES_PATH to
the location
of that file.

Tasks: TOP => default
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in
D:/Redmine/ruby/lib/ruby/gems/2.6.0/gems/mimemagic-0.4.3 for inspection.
Results logged to
D:/Redmine/ruby/lib/ruby/gems/2.6.0/extensions/x64-mingw32/2.6.0/mimemagic-0.4.3/gem_make.out

An error occurred while installing mimemagic (0.4.3), and Bundler cannot
continue.
Make sure that `gem install mimemagic -v '0.4.3' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  mimemagic

**Comment by Cloud-zack** [comment]
How to solve it?

**Comment by HugoHasenbein** [comment]
Dear Zac,

please try to delete the following lines from

D:/Redmine/apps/redmine/htdocs/plugins/redmine_more_previews/converters/zippy/Gemfile

gem 'rubyzip'

I assume, other plugins load rubyzip as well and so they are in conflict. zippy should work with any version of rubyzip.

**Comment by Cloud-zack** [comment]
That doesn't work. The error message hasn't changed

**Comment by Cloud-zack** [comment]
execute"bundle exec rake redmine:plugins:migrate" error log:
![error](https://user-images.githubusercontent.com/84425670/118762609-18345a00-b8a9-11eb-8a54-e9596940adf3.jpg)

Could not find gem 'mimemagic x64-mingw32' in any of the gem sources listed in your Gemfile or in gems cached in vendor/cache.
Run `bundle install` to install missing gems.

**Comment by HugoHasenbein** [comment]
Dear Zac,

did you install the missing gem by running `bundle install` ?

**Comment by Cloud-zack** [comment]
Thank you, I will try to install the missing gem，later check to see if this problem exists

**Comment by Cloud-zack** [comment]
Hi!
After installing the missing gem, the plugin installation still fails,error log：

rake aborted!
Errno::EISDIR: Is a directory @ rb_sysopen - D:/Redmine/apps/redmine/htdocs/plugins
D:/Redmine/apps/redmine/htdocs/config/application.rb:18:in `<top (required)>'
D:/Redmine/apps/redmine/htdocs/Rakefile:5:in `require'
D:/Redmine/apps/redmine/htdocs/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
![Error](https://user-images.githubusercontent.com/84425670/119113097-53748b80-ba57-11eb-8080-b9e52427885d.jpg)
