### ISSUE TITLE
Error create preview image in bitnami Redmine (debian)

### ISSUE THREAD

**Issue by Omega-kun** [HugoHasenbein/redmine_more_previews#23]
I have installed bitnami redmine
Environment:
  Redmine version                4.2.1.stable
  Ruby version                   2.6.7-p197 (2021-04-05) [x86_64-linux]
  Rails version                  5.2.5
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.14.1
  Git                            2.31.1
  Filesystem                     
Redmine plugins:
  mega_calendar                  1.7.4
  redmine_custom_workflows       1.0.5
  redmine_drive                  1.1.0
  redmine_issues_tree            0.0.14
  redmine_more_previews          2.0.3
  redmine_resources              1.0.5
  scrum                          0.21.0
  view_customize                 2.8.1

PDF converter work. But when i try to open office file (LibreOffice 6.1.5.2 10(Build:2) install), i have recived error

Started GET "/attachments/more_preview/2/index.pdf?drive_entry=true" for 172.16.30.246 at 2021-06-02 07:46:23 +0000
Processing by AttachmentsController#more_preview as PDF
  Parameters: {"drive_entry"=>"true", "id"=>"2"}
  Current user: asolyanik (id=7)
Creating preview with Libre failed (pid 7910 exit 1):
Command: cd '/tmp/d20210602-5398-1nns1qq'; soffice --headless --convert-to pdf --outdir '/tmp/d20210602-5398-1nns1qq' -env:UserInstallation=file:///tmp/d20210602-5398-qfb96q/user_installation '/opt/bitnami/apps/redmine/htdocs/files/2021/05/210531114422_d5bf80d3fcedc5c7f5a6dda0b2d538c6.xlsx'; mv './210531114422_d5bf80d3fcedc5c7f5a6dda0b2d538c6.pdf' '/tmp/d20210602-5398-1nns1qq/index.pdf'
An error occured while generating preview for /opt/bitnami/apps/redmine/htdocs/files/2021/05/210531114422_d5bf80d3fcedc5c7f5a6dda0b2d538c6.xlsx
Exception was: ConverterShellError

and in log file i see
Jun 15 10:14:22 redmine-dev kernel: kauditd_printk_skb: 37 callbacks suppressed
Jun 15 10:14:22 redmine-dev kernel: audit: type=1400 audit(1623752062.043:6203): apparmor="ALLOWED" operation="open" profile="libreoffice-oopslash" name="/opt/bitnami/common/lib/libz.so.1.2.11" pid=26633 comm="oosplash" requested_mask="r" denied_mask="r" fsuid=1 ouid=0
Jun 15 10:14:22 redmine-dev kernel: audit: type=1400 audit(1623752062.043:6204): apparmor="ALLOWED" operation="file_mmap" profile="libreoffice-oopslash" name="/opt/bitnami/common/lib/libz.so.1.2.11" pid=26633 comm="oosplash" requested_mask="rm" denied_mask="rm" fsuid=1 ouid=0
Jun 15 10:14:22 redmine-dev kernel: audit: type=1400 audit(1623752062.047:6205): apparmor="ALLOWED" operation="open" profile="libreoffice-soffice" name="/opt/bitnami/common/lib/libz.so.1.2.11" pid=26650 comm="soffice.bin" requested_mask="r" denied_mask="r" fsuid=1 ouid=0
Jun 15 10:14:22 redmine-dev kernel: audit: type=1400 audit(1623752062.047:6206): apparmor="ALLOWED" operation="file_mmap" profile="libreoffice-soffice" name="/opt/bitnami/common/lib/libz.so.1.2.11" pid=26650 comm="soffice.bin" requested_mask="rm" denied_mask="rm" fsuid=1 ouid=0
Jun 15 10:14:22 redmine-dev kernel: audit: type=1400 audit(1623752062.051:6207): apparmor="ALLOWED" operation="open" profile="libreoffice-soffice" name="/opt/bitnami/common/lib/libxml2.so.2.9.4" pid=26650 comm="soffice.bin" requested_mask="r" denied_mask="r" fsuid=1 ouid=0
Jun 15 10:14:22 redmine-dev kernel: audit: type=1400 audit(1623752062.051:6208): apparmor="ALLOWED" operation="file_mmap" profile="libreoffice-soffice" name="/opt/bitnami/common/lib/libxml2.so.2.9.4" pid=26650 comm="soffice.bin" requested_mask="rm" denied_mask="rm" fsuid=1 ouid=0
Jun 15 10:14:22 redmine-dev kernel: audit: type=1400 audit(1623752062.051:6209): apparmor="ALLOWED" operation="open" profile="libreoffice-soffice" name="/opt/bitnami/common/lib/libexpat.so.1.6.2" pid=26650 comm="soffice.bin" requested_mask="r" denied_mask="r" fsuid=1 ouid=0
Jun 15 10:14:22 redmine-dev kernel: audit: type=1400 audit(1623752062.051:6210): apparmor="ALLOWED" operation="file_mmap" profile="libreoffice-soffice" name="/opt/bitnami/common/lib/libexpat.so.1.6.2" pid=26650 comm="soffice.bin" requested_mask="rm" denied_mask="rm" fsuid=1 ouid=0
Jun 15 10:14:22 redmine-dev kernel: audit: type=1400 audit(1623752062.051:6211): apparmor="ALLOWED" operation="open" profile="libreoffice-soffice" name="/opt/bitnami/common/lib/libxslt.so.1.1.33" pid=26650 comm="soffice.bin" requested_mask="r" denied_mask="r" fsuid=1 ouid=0
Jun 15 10:14:22 redmine-dev kernel: audit: type=1400 audit(1623752062.051:6212): apparmor="ALLOWED" operation="file_mmap" profile="libreoffice-soffice" name="/opt/bitnami/common/lib/libxslt.so.1.1.33" pid=26650 comm="soffice.bin" requested_mask="rm" denied_mask="rm" fsuid=1 ouid=0

II tried different options with setting access to folders, but it did not help. Moreover, if you execute the command for conversion from the command line, it is executed and the file with the preview is created. In what direction can i see the reason for the plugin not working?

**Comment by HugoHasenbein** [comment]
Dear Omega,

I do see two oddities:

The Attachments Controller is called with a parameter "drive_entry", which does not come from my plugin. I suspect your plugin redmine_drive to alter something. Try running redmine without the plugin for testing purposes only and give feedback if that solves the problem

Further,there are some suspicious logfile entries, alike
> requested_mask="rm" denied_mask="rm" fsuid=1 ouid=0
> 

This reads as if some program denies libre to start. Does bitnami provide security mechanisms to prevnet running of external programs?

Best regards

Stephan
