### ISSUE TITLE
Issues with Redmine 4.2.1 / Ruby 2.7.2

### ISSUE THREAD

**Issue by sunrez** [HugoHasenbein/redmine_more_previews#24]
Hi,

I have tried to install this plug-in and think there might be some compatibility issue with the latest (released) Redmine & Ruby.

Host OS is Debian 10.  Ruby 2.7.2 was compiled from source -- not using distribution Ruby, Redmine installed from released source, permissions are all correct.

I think it might be related to mimemagic and Marcel (I think the latest Ruby doesn't include mimemagic due to some licensing issues?).  I also ran into a mimemagic issue when trying to install your other plug-in: redmine_attachment_categories

**Note 1:**  Had to comment out 'rubyzip' since there was some odd version class between this another Redmine Gemfile that had specific rubyzip > 1.2.2

**Note 2:**  I have done gem install mimemagic as well and the 'bundle install' before invoking the web server.

**Note 3:**  Error goes away when I delete this plug-in

**Error:**

bundle exec rails server webrick -e production
/usr/local/bin/ruby: warning: shebang line ending with \r may cause problems
=> Booting WEBrick
=> Rails 5.2.5 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
Exiting
Traceback (most recent call last):
	81: from bin/rails:4:in `<main>'
	80: from bin/rails:4:in `require'
	79: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-5.2.5/lib/rails/commands.rb:18:in `<top (required)>'
	78: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-5.2.5/lib/rails/command.rb:46:in `invoke'
	77: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-5.2.5/lib/rails/command/base.rb:69:in `perform'
	76: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	75: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	74: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	73: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-5.2.5/lib/rails/commands/server/server_command.rb:142:in `perform'
	72: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-5.2.5/lib/rails/commands/server/server_command.rb:142:in `tap'
	71: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-5.2.5/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	70: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-5.2.5/lib/rails/commands/server/server_command.rb:53:in `start'
	69: from /usr/local/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:311:in `start'
	68: from /usr/local/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling'
	67: from /usr/local/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start'
	66: from /usr/local/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
	65: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-5.2.5/lib/rails/commands/server/server_command.rb:27:in `app'
	64: from /usr/local/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
	63: from /usr/local/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	62: from /usr/local/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
	61: from /usr/local/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
	60: from /usr/local/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
	59: from /usr/local/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
	58: from config.ru:3:in `block in <main>'
	57: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require'
	56: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:257:in `load_dependency'
	55: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `block in require'
	54: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require'
	53: from /var/www/redmine/config/environment.rb:16:in `<top (required)>'
	52: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-5.2.5/lib/rails/application.rb:361:in `initialize!'
	51: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-5.2.5/lib/rails/initializable.rb:60:in `run_initializers'
	50: from /usr/local/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
	49: from /usr/local/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
	48: from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
	47: from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `call'
	46: from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each'
	45: from /usr/local/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
	44: from /usr/local/lib/ruby/2.7.0/tsort.rb:415:in `each_strongly_connected_component_from'
	43: from /usr/local/lib/ruby/2.7.0/tsort.rb:415:in `call'
	42: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-5.2.5/lib/rails/initializable.rb:50:in `tsort_each_child'
	41: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-5.2.5/lib/rails/initializable.rb:50:in `each'
	40: from /usr/local/lib/ruby/2.7.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	39: from /usr/local/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
	38: from /usr/local/lib/ruby/2.7.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	37: from /usr/local/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	36: from /usr/local/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
	35: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-5.2.5/lib/rails/initializable.rb:61:in `block in run_initializers'
	34: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-5.2.5/lib/rails/initializable.rb:32:in `run'
	33: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-5.2.5/lib/rails/initializable.rb:32:in `instance_exec'
	32: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-5.2.5/lib/rails/engine.rb:619:in `block in <class:Engine>'
	31: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-5.2.5/lib/rails/engine.rb:619:in `each'
	30: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-5.2.5/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
	29: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-5.2.5/lib/rails/engine.rb:662:in `load_config_initializer'
	28: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-5.2.5/lib/active_support/notifications.rb:170:in `instrument'
	27: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-5.2.5/lib/rails/engine.rb:663:in `block in load_config_initializer'
	26: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:285:in `load'
	25: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:257:in `load_dependency'
	24: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:285:in `block in load'
	23: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:285:in `load'
	22: from /var/www/redmine/config/initializers/30-redmine.rb:20:in `<top (required)>'
	21: from /var/www/redmine/lib/redmine/plugin.rb:178:in `load'
	20: from /var/www/redmine/lib/redmine/plugin.rb:178:in `each'
	19: from /var/www/redmine/lib/redmine/plugin.rb:187:in `block in load'
	18: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require'
	17: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:257:in `load_dependency'
	16: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `block in require'
	15: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require'
	14: from /var/www/redmine/plugins/redmine_more_previews/init.rb:69:in `<top (required)>'
	13: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require'
	12: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:257:in `load_dependency'
	11: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `block in require'
	10: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require'
	 9: from /var/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews.rb:31:in `<top (required)>'
	 8: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require'
	 7: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:257:in `load_dependency'
	 6: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `block in require'
	 5: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require'
	 4: from /var/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/patches/repository_patch.rb:24:in `<top (required)>'
	 3: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require'
	 2: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:257:in `load_dependency'
	 1: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/lib/ruby/gems/2.7.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require': cannot load such file -- mimemagic/overlay (LoadError)

**Comment by HugoHasenbein** [comment]
in the Gemfile:

-- gem 'mimemagic'
++ gem 'mimemagic', ~> '0.3.8'

please give feedback, if that solves the issue

**Comment by sunrez** [comment]
Hi,

After using this syntax:  gem 'mimemagic', '~> 0.3.8'

I was able to get the plug-in to load, thank you!  I'll do more testing over the weekend and report back if there are issues.

I'll also try this for your other plug-in and report back.

Thank you for the plug-in and also for the quick response!

**Comment by HugoHasenbein** [comment]
gem 'mimemagic', '~> 0.3.8' solved the problem
