### ISSUE TITLE
Error at installation - mimemagic

### ISSUE THREAD

**Issue by kma-systo** [HugoHasenbein/redmine_more_previews#25]
Hello,

I can't manage to install this plugin. Here is my redmine details : 

Environment:
  Redmine version                4.2.1.stable
  Ruby version                   2.7.2-p137 (2020-10-01) [x86_64-linux]
  Rails version                  5.2.5
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.25.1
  Filesystem                     
Redmine plugins:
  no plugin installed

My issue : 
I installed the directory in redmine's plugin directory, and then when bundle install : 

![plugin](https://user-images.githubusercontent.com/87123001/124900449-5c0e2a80-dfe1-11eb-8437-d91d66d5dead.png)

Does someone have a clue on what's wrong please ?

Thank you.

**Comment by kma-systo** [comment]
Sorry i don't know how to do a clean display :/

**Comment by HugoHasenbein** [comment]
opps...
please try Version 2.0.5 now on GitHub

**Comment by kma-systo** [comment]
Hello.

Thank you for your quick answer !

I see what you've changed, the ~> ' 0.3.8'  to  '~> 0.3.8'  i actually tried this earlier, but it gave me those error now : 

![plugin2](https://user-images.githubusercontent.com/87123001/124912245-02602d00-dfee-11eb-82a9-a83ccc9ff706.png)

 I'm not very familiar with the gem management. Do you see what's wrong in here ? Thank you

**Comment by HugoHasenbein** [comment]
Dear User,

yes, the problematic is due to the major license change in mimemagic. In line 108 of Redmine's Gemfile change the line as ist is in the plugins Gemfile.

best regards

Stephan

**Comment by kma-systo** [comment]
Thank you for your answer. I actually did the opposite : 

[root@xe-redmine-v4-prod-web plugins]# cat redmine_more_previews/converters/zippy/Gemfile 
#gem 'rubyzip'
gem 'zlib'

And I kept it in the redmine gem file : 

gem 'rubyzip', '~> 2.3.0'

It's working now

**Comment by HugoHasenbein** [comment]
The problem arose with mimemagic, not with rubyzip?

**Comment by kma-systo** [comment]
The initial problem was with mimemagic but since you corrected the code, the second issue was with the double version requirement for rubyzip
