### ISSUE TITLE
"Plugins settings" section empty

### ISSUE THREAD

**Issue by digchg-mweiss** [HugoHasenbein/redmine_more_previews#26]
There are no entries below the "Plugins settings" section. What am I doing wrong?

![grafik](https://user-images.githubusercontent.com/74358275/126317278-eabe0280-c454-40cb-8321-4858822f4145.png)

I can see the following log entries on Redmine startup:
```
App 78 output: /opt/bitnami/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/lib/converter.rb:67: warning: already initialized constant RedmineMorePreviews::Converter::FORMATS

App 78 output: /bitnami/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/lib/converter.rb:67: warning: previous definition of FORMATS was here

App 78 output: /opt/bitnami/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/lib/converter.rb:68: warning: already initialized constant RedmineMorePreviews::Converter::FORMAT_MIMES

App 78 output: /bitnami/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/lib/converter.rb:68: warning: previous definition of FORMAT_MIMES was here
```
![grafik](https://user-images.githubusercontent.com/74358275/126317901-76da160e-b6a6-429d-9f1d-78a352600d4a.png)

**Comment by HugoHasenbein** [comment]
there seem to be two instances / versions of the plugin to be installed, one in /bitnami, the other in /opt/bitnami. The plugins interfere with each other.

**Comment by digchg-mweiss** [comment]
No it's just a Link:
`bitnami@e42d2b3517dd:/opt/bitnami/redmine$ ls plugins -lsa
0 lrwxrwxrwx 1 root root 24 Jul 20 10:31 plugins -> /bitnami/redmine/plugins`

That's the standard setup of the popular [Bitnami Docker Image for Redmine](https://hub.docker.com/r/bitnami/redmine/)

**Comment by HugoHasenbein** [comment]
it seems, the link is followed by rails, thus executing the plugin_inialization twice

**Comment by digchg-mweiss** [comment]
OK, so it's a rails issue? I also have two other plugins running w/o issues.
I am not experienced in rails. Any ideas how to solve this?
If not you can close the ticket.
Thanks in advance und Liebe Grüße!

**Comment by HugoHasenbein** [comment]
let's assume, the rails log was only a warning: are converters installed? look in plugins/redmine_more_previes/converters

**Comment by digchg-mweiss** [comment]
The documentation says:
![grafik](https://user-images.githubusercontent.com/74358275/126325376-a975455b-ba23-4bc6-920d-243c422726f4.png)

So the files should be the same as from the repo:
![grafik](https://user-images.githubusercontent.com/74358275/126325473-31746f05-a402-4605-993c-c185f18dfa16.png)

**Comment by HugoHasenbein** [comment]
looks good.
can you open a rails console like

rails console production

and then in the console

2.7.0 :002 > RedmineMorePreviews::Converter.all.map(&:name)

 => ["Cliff", "Libre", "Mark", "Nil Text", "Peek", "Zippy"]

does your console reveal the same?

**Comment by digchg-mweiss** [comment]
Loading production environment (Rails 5.2.5)
irb(main):001:0> RedmineMorePreviews::Converter.all.map(&:name)
=> []

**Comment by HugoHasenbein** [comment]
what happens on RedmineMorePreviews::Converter.load in the rails console

**Comment by digchg-mweiss** [comment]
irb(main):002:0> RedmineMorePreviews::Converter.load
=> ["/opt/bitnami/redmine/plugins/redmine_more_previews/converters/cliff", "/opt/bitnami/redmine/plugins/redmine_more_previews/converters/libre", "/opt/bitnami/redmine/plugins/redmine_more_previews/converters/mark", "/opt/bitnami/redmine/plugins/redmine_more_previews/converters/nil_text", "/opt/bitnami/redmine/plugins/redmine_more_previews/converters/peek"]

**Comment by HugoHasenbein** [comment]
now do

RedmineMorePreviews::Converter.load

RedmineMorePreviews::Converter.all.map(&:name)

**Comment by digchg-mweiss** [comment]
irb(main):004:0> RedmineMorePreviews::Converter.load
=> ["/opt/bitnami/redmine/plugins/redmine_more_previews/converters/cliff", "/opt/bitnami/redmine/plugins/redmine_more_previews/converters/libre", "/opt/bitnami/redmine/plugins/redmine_more_previews/converters/mark", "/opt/bitnami/redmine/plugins/redmine_more_previews/converters/nil_text", "/opt/bitnami/redmine/plugins/redmine_more_previews/converters/peek"]
irb(main):005:0> RedmineMorePreviews::Converter.all.map(&:name)
=> []

**Comment by HugoHasenbein** [comment]
and

RedmineMorePreviews::Converter.register(:cliff){mime_types(:eml => {:formats => [:html], :mime => "message/rfc822", :icon => "eml.png" })}

**Comment by digchg-mweiss** [comment]
irb(main):006:0> RedmineMorePreviews::Converter.register(:cliff){mime_types(:eml => {:formats => [:html], :mime => "message/rfc822", :icon => "eml.png" })}
=> #<RedmineMorePreviews::Converter:0x00005645d7caac60 @id=:cliff, @mime_types={:eml=>{:formats=>[:html], :mime=>"message/rfc822", :icon=>"eml.png", :active=>true}}, @name="Cliff", @class_name="Cliff", @directory="/opt/bitnami/redmine/plugins/redmine_more_previews/converters/cliff", @threadsafe=false, @timeout=5, @shell_api="open3", @converter_class=Cliff, @semaphore=#<Thread::Mutex:0x00005645d7d3e3c0>>

irb(main):007:0> RedmineMorePreviews::Converter.all.map(&:name)
=> ["Cliff"]

**Comment by HugoHasenbein** [comment]
hard to tackle - it seems, redmine gets confused with  the parallel /opt/bitnami and /bitnami directories
