### ISSUE TITLE
Plugin is not requiring LibreOffice

### ISSUE THREAD

**Issue by kyvaith** [HugoHasenbein/redmine_more_previews#36]
Hi, I have a problem. Plugin is not requarint LibreOffice and since that the config are empty. Please help

![image](https://user-images.githubusercontent.com/107579/146187466-d9180a67-4e3c-489d-8a40-8ff58594ccd3.png)
![image](https://user-images.githubusercontent.com/107579/146187512-836384e3-054b-4621-9878-10668abaf700.png)

**Comment by HugoHasenbein** [comment]
Dear Toamsz,

it should show one check box per installed sub plugin in ~/plugins/redmine_more_previews/converters.

I do not understand "Plugin is not requarint LibreOffice and since that". Do you mean, you did not install LibreOffice?

Do you have a log file excerpt?

best regards

Stephan

**Comment by kyvaith** [comment]
As you can see I've installed your plugin and I installed LibreOffice. Plugins settings section is empty and in Information tab don't show LibreOffice

**Comment by HugoHasenbein** [comment]
did you migrate?

**Comment by kyvaith** [comment]
Sure I did.

czw., 16 gru 2021, 16:04 użytkownik Dr. Stephan Wenzel <
***@***.***> napisał:

**Comment by kyvaith** [comment]
Just to clarify - I've installed whole bunch of plugins (and fixed minor gem issues) and everything works well, except Your plugin. I see no error in logs. soffice command from CLI works well

**Comment by HugoHasenbein** [comment]
Dear Tomasz,

currently, the plugin runs on presumably several thousand installations. Still, I learn every day what may get into conflict with my plugin. I am willing to help, but I need some helpful information from you

Login in into your computer, not in redmine, as your redmine user, under which your redmine installation runs

Start a rails console

on Linux:

rails c -e production
2.7.2 :001 > RedmineMorePreviews::Converter.all.map(&:id)

it should answer with:

=> [:cliff, :libre, :mark, :nil_text, :peek, :zippy]

Can you share the answer of your system?

**Comment by kyvaith** [comment]
This is what I get

Loading production environment (Rails 5.2.6)
irb(main):001:0> RedmineMorePreviews::Converter.all.map(&:id)
=> []
irb(main):002:0>

**Comment by HugoHasenbein** [comment]
Good, this is, what I have expected.

Then list all the files / directories in plugins/redmine_more_previews/converters together with the access rights.

**Comment by kyvaith** [comment]
bitnami@PRODV-MBRM01:/opt/bitnami/redmine/plugins/redmine_more_previews$ tree -pufia
.
[drwxr-xr-x bitnami ]  ./app
[drwxr-xr-x bitnami ]  ./app/views
[drwxr-xr-x bitnami ]  ./app/views/attachments
[-rw-r--r-- bitnami ]  ./app/views/attachments/more_preview.html.erb
[drwxr-xr-x bitnami ]  ./app/views/hooks
[drwxr-xr-x bitnami ]  ./app/views/hooks/redmine_more_previews
[-rw-r--r-- bitnami ]  ./app/views/hooks/redmine_more_previews/_icon_css.html.erb
[drwxr-xr-x bitnami ]  ./app/views/repositories
[-rw-r--r-- bitnami ]  ./app/views/repositories/more_preview.html.erb
[drwxr-xr-x bitnami ]  ./app/views/settings
[drwxr-xr-x bitnami ]  ./app/views/settings/redmine_more_previews
[-rw-r--r-- bitnami ]  ./app/views/settings/redmine_more_previews/_settings.html.erb
[drwxr-xr-x bitnami ]  ./app/views/settings/redmine_more_previews/welcome
[-rw-r--r-- bitnami ]  ./app/views/settings/redmine_more_previews/welcome/_greeting.de.html.erb
[-rw-r--r-- bitnami ]  ./app/views/settings/redmine_more_previews/welcome/_greeting.en.html.erb
[-rw-r--r-- bitnami ]  ./app/views/settings/redmine_more_previews/welcome/_greeting.es.html.erb
[-rw-r--r-- bitnami ]  ./app/views/settings/redmine_more_previews/welcome/_greeting.fr.html.erb
[-rw-r--r-- bitnami ]  ./app/views/settings/redmine_more_previews/welcome/_greeting.html.erb
[-rw-r--r-- bitnami ]  ./app/views/settings/redmine_more_previews/welcome/_greeting.ja.html.erb
[-rw-r--r-- bitnami ]  ./app/views/settings/redmine_more_previews/welcome/_greeting.pt-br.html.erb
[-rw-r--r-- bitnami ]  ./app/views/settings/redmine_more_previews/welcome/_greeting.pt.html.erb
[-rw-r--r-- bitnami ]  ./app/views/settings/redmine_more_previews/welcome/_greeting.ru.html.erb
[-rw-r--r-- bitnami ]  ./app/views/settings/redmine_more_previews/welcome/_greeting.zh.html.erb
[drwxr-xr-x bitnami ]  ./assets
[drwxr-xr-x bitnami ]  ./assets/images
[-rw-r--r-- bitnami ]  ./assets/images/Logo.png
[drwxr-xr-x bitnami ]  ./config
[drwxr-xr-x bitnami ]  ./config/locales
[-rw-r--r-- bitnami ]  ./config/locales/de.yml
[-rw-r--r-- bitnami ]  ./config/locales/en.yml
[-rw-r--r-- bitnami ]  ./config/locales/es.yml
[-rw-r--r-- bitnami ]  ./config/locales/fr.yml
[-rw-r--r-- bitnami ]  ./config/locales/jp.yml
[-rw-r--r-- bitnami ]  ./config/locales/pt-br.yml
[-rw-r--r-- bitnami ]  ./config/locales/pt.yml
[-rw-r--r-- bitnami ]  ./config/locales/ru.yml
[-rw-r--r-- bitnami ]  ./config/locales/zh.yml
[-rw-r--r-- bitnami ]  ./config/routes.rb
[drwxr-xr-x bitnami ]  ./converters
[drwxr-xr-x bitnami ]  ./converters/cliff
[drwxr-xr-x bitnami ]  ./converters/cliff/app
[drwxr-xr-x bitnami ]  ./converters/cliff/app/views
[drwxr-xr-x bitnami ]  ./converters/cliff/app/views/redmine_more_previews
[drwxr-xr-x bitnami ]  ./converters/cliff/app/views/redmine_more_previews/hooks
[-rw-r--r-- bitnami ]  ./converters/cliff/app/views/redmine_more_previews/hooks/_cliff_preview_attachment_contextual.html.erb
[-rw-r--r-- bitnami ]  ./converters/cliff/app/views/redmine_more_previews/hooks/_cliff_preview_attachment_top.html.erb
[-rw-r--r-- bitnami ]  ./converters/cliff/app/views/redmine_more_previews/hooks/_cliff_preview_repository_entry_contextual.html.erb
[-rw-r--r-- bitnami ]  ./converters/cliff/app/views/redmine_more_previews/hooks/_cliff_preview_repository_entry_top.html.erb
[drwxr-xr-x bitnami ]  ./converters/cliff/assets
[drwxr-xr-x bitnami ]  ./converters/cliff/assets/images
[-rw-r--r-- bitnami ]  ./converters/cliff/assets/images/eml.png
[-rw-r--r-- bitnami ]  ./converters/cliff/assets/images/logo.png
[drwxr-xr-x bitnami ]  ./converters/cliff/config
[drwxr-xr-x bitnami ]  ./converters/cliff/config/locales
[-rw-r--r-- bitnami ]  ./converters/cliff/config/locales/de.yml
[-rw-r--r-- bitnami ]  ./converters/cliff/config/locales/en.yml
[-rw-r--r-- bitnami ]  ./converters/cliff/Gemfile
[-rw-r--r-- bitnami ]  ./converters/cliff/init.rb
[drwxr-xr-x bitnami ]  ./converters/cliff/lib
[drwxr-xr-x bitnami ]  ./converters/cliff/lib/cliff
[-rw-r--r-- bitnami ]  ./converters/cliff/lib/cliff/attachments.html.erb
[-rw-r--r-- bitnami ]  ./converters/cliff/lib/cliff/fields.html.erb
[-rw-r--r-- bitnami ]  ./converters/cliff/lib/cliff/headers.html.erb
[-rw-r--r-- bitnami ]  ./converters/cliff/lib/cliff/pre.html.erb
[-rw-r--r-- bitnami ]  ./converters/cliff/lib/cliff.rb
[drwxr-xr-x bitnami ]  ./converters/cliff/lib/hooks
[-rw-r--r-- bitnami ]  ./converters/cliff/lib/hooks/cliff_eml_contextual_hook.rb
[-rw-r--r-- bitnami ]  ./converters/cliff/lib/hooks/cliff_eml_top_hook.rb
[-rw-r--r-- bitnami ]  ./converters/cliff/lib/lib.rb
[drwxr-xr-x bitnami ]  ./converters/libre
[drwxr-xr-x bitnami ]  ./converters/libre/assets
[drwxr-xr-x bitnami ]  ./converters/libre/assets/images
[-rw-r--r-- bitnami ]  ./converters/libre/assets/images/doc.png
[-rw-r--r-- bitnami ]  ./converters/libre/assets/images/docx.png
[-rw-r--r-- bitnami ]  ./converters/libre/assets/images/dot.png
[-rw-r--r-- bitnami ]  ./converters/libre/assets/images/logo.png
[-rw-r--r-- bitnami ]  ./converters/libre/assets/images/odf.png
[-rw-r--r-- bitnami ]  ./converters/libre/assets/images/odg.png
[-rw-r--r-- bitnami ]  ./converters/libre/assets/images/odi.png
[-rw-r--r-- bitnami ]  ./converters/libre/assets/images/odp.png
[-rw-r--r-- bitnami ]  ./converters/libre/assets/images/ods.png
[-rw-r--r-- bitnami ]  ./converters/libre/assets/images/ppt.png
[-rw-r--r-- bitnami ]  ./converters/libre/assets/images/pptx.png
[-rw-r--r-- bitnami ]  ./converters/libre/assets/images/swf.png
[-rw-r--r-- bitnami ]  ./converters/libre/assets/images/xls.png
[-rw-r--r-- bitnami ]  ./converters/libre/assets/images/xlsx.png
[drwxr-xr-x bitnami ]  ./converters/libre/config
[drwxr-xr-x bitnami ]  ./converters/libre/config/locales
[-rw-r--r-- bitnami ]  ./converters/libre/config/locales/de.yml
[-rw-r--r-- bitnami ]  ./converters/libre/config/locales/en.yml
[-rw-r--r-- bitnami ]  ./converters/libre/init.rb
[drwxr-xr-x bitnami ]  ./converters/libre/lib
[-rw-r--r-- bitnami ]  ./converters/libre/lib/libre.rb
[drwxr-xr-x bitnami ]  ./converters/mark
[drwxr-xr-x bitnami ]  ./converters/mark/assets
[drwxr-xr-x bitnami ]  ./converters/mark/assets/images
[-rw-r--r-- bitnami ]  ./converters/mark/assets/images/logo.png
[-rw-r--r-- bitnami ]  ./converters/mark/assets/images/markdown.png
[-rw-r--r-- bitnami ]  ./converters/mark/assets/images/tex.png
[drwxr-xr-x bitnami ]  ./converters/mark/config
[drwxr-xr-x bitnami ]  ./converters/mark/config/locales
[-rw-r--r-- bitnami ]  ./converters/mark/config/locales/de.yml
[-rw-r--r-- bitnami ]  ./converters/mark/config/locales/en.yml
[-rw-r--r-- bitnami ]  ./converters/mark/init.rb
[drwxr-xr-x bitnami ]  ./converters/mark/lib
[-rw-r--r-- bitnami ]  ./converters/mark/lib/mark.rb
[drwxr-xr-x bitnami ]  ./converters/nil_text
[drwxr-xr-x bitnami ]  ./converters/nil_text/app
[drwxr-xr-x bitnami ]  ./converters/nil_text/app/views
[drwxr-xr-x bitnami ]  ./converters/nil_text/app/views/settings
[drwxr-xr-x bitnami ]  ./converters/nil_text/app/views/settings/redmine_more_previews
[drwxr-xr-x bitnami ]  ./converters/nil_text/app/views/settings/redmine_more_previews/nil_text
[-rw-r--r-- bitnami ]  ./converters/nil_text/app/views/settings/redmine_more_previews/nil_text/_settings.html.erb
[drwxr-xr-x bitnami ]  ./converters/nil_text/assets
[drwxr-xr-x bitnami ]  ./converters/nil_text/assets/images
[-rw-r--r-- bitnami ]  ./converters/nil_text/assets/images/logo.png
[drwxr-xr-x bitnami ]  ./converters/nil_text/config
[drwxr-xr-x bitnami ]  ./converters/nil_text/config/locales
[-rw-r--r-- bitnami ]  ./converters/nil_text/config/locales/de.yml
[-rw-r--r-- bitnami ]  ./converters/nil_text/config/locales/en.yml
[-rw-r--r-- bitnami ]  ./converters/nil_text/init.rb
[drwxr-xr-x bitnami ]  ./converters/nil_text/lib
[-rw-r--r-- bitnami ]  ./converters/nil_text/lib/nil_text.rb
[drwxr-xr-x bitnami ]  ./converters/peek
[drwxr-xr-x bitnami ]  ./converters/peek/assets
[drwxr-xr-x bitnami ]  ./converters/peek/assets/images
[-rw-r--r-- bitnami ]  ./converters/peek/assets/images/logo.png
[-rw-r--r-- bitnami ]  ./converters/peek/init.rb
[drwxr-xr-x bitnami ]  ./converters/peek/lib
[-rw-r--r-- bitnami ]  ./converters/peek/lib/peek.rb
[drwxr-xr-x bitnami ]  ./converters/zippy
[drwxr-xr-x bitnami ]  ./converters/zippy/assets
[drwxr-xr-x bitnami ]  ./converters/zippy/assets/images
[-rw-r--r-- bitnami ]  ./converters/zippy/assets/images/gz.png
[-rw-r--r-- bitnami ]  ./converters/zippy/assets/images/logo.png
[-rw-r--r-- bitnami ]  ./converters/zippy/assets/images/tar.png
[-rw-r--r-- bitnami ]  ./converters/zippy/assets/images/tgz.png
[-rw-r--r-- bitnami ]  ./converters/zippy/assets/images/zip.png
[drwxr-xr-x bitnami ]  ./converters/zippy/config
[drwxr-xr-x bitnami ]  ./converters/zippy/config/locales
[-rw-r--r-- bitnami ]  ./converters/zippy/config/locales/de.yml
[-rw-r--r-- bitnami ]  ./converters/zippy/config/locales/en.yml
[-rw-r--r-- bitnami ]  ./converters/zippy/Gemfile
[-rw-r--r-- bitnami ]  ./converters/zippy/init.rb
[drwxr-xr-x bitnami ]  ./converters/zippy/lib
[-rw-r--r-- bitnami ]  ./converters/zippy/lib/array.rb
[-rw-r--r-- bitnami ]  ./converters/zippy/lib/zippy.rb
[drwxr-xr-x bitnami ]  ./doc
[drwxr-xr-x bitnami ]  ./doc/cliff
[-rw-r--r-- bitnami ]  ./doc/cliff/logo.png
[drwxr-xr-x bitnami ]  ./doc/libre
[-rw-r--r-- bitnami ]  ./doc/libre/logo.png
[drwxr-xr-x bitnami ]  ./doc/mark
[-rw-r--r-- bitnami ]  ./doc/mark/logo.png
[drwxr-xr-x bitnami ]  ./doc/nil_text
[-rw-r--r-- bitnami ]  ./doc/nil_text/logo.png
[drwxr-xr-x bitnami ]  ./doc/peek
[-rw-r--r-- bitnami ]  ./doc/peek/logo.png
[drwxr-xr-x bitnami ]  ./doc/zippy
[-rw-r--r-- bitnami ]  ./doc/zippy/logo.png
[-rw-r--r-- bitnami ]  ./Gemfile
[drwxr-xr-x bitnami ]  ./.git
[drwxr-xr-x bitnami ]  ./.git/branches
[-rw-r--r-- bitnami ]  ./.git/config
[-rw-r--r-- bitnami ]  ./.git/description
[-rw-r--r-- bitnami ]  ./.git/HEAD
[drwxr-xr-x bitnami ]  ./.git/hooks
[-rwxr-xr-x bitnami ]  ./.git/hooks/applypatch-msg.sample
[-rwxr-xr-x bitnami ]  ./.git/hooks/commit-msg.sample
[-rwxr-xr-x bitnami ]  ./.git/hooks/fsmonitor-watchman.sample
[-rwxr-xr-x bitnami ]  ./.git/hooks/post-update.sample
[-rwxr-xr-x bitnami ]  ./.git/hooks/pre-applypatch.sample
[-rwxr-xr-x bitnami ]  ./.git/hooks/pre-commit.sample
[-rwxr-xr-x bitnami ]  ./.git/hooks/pre-merge-commit.sample
[-rwxr-xr-x bitnami ]  ./.git/hooks/prepare-commit-msg.sample
[-rwxr-xr-x bitnami ]  ./.git/hooks/pre-push.sample
[-rwxr-xr-x bitnami ]  ./.git/hooks/pre-rebase.sample
[-rwxr-xr-x bitnami ]  ./.git/hooks/pre-receive.sample
[-rwxr-xr-x bitnami ]  ./.git/hooks/push-to-checkout.sample
[-rwxr-xr-x bitnami ]  ./.git/hooks/update.sample
[-rw-r--r-- bitnami ]  ./.git/index
[drwxr-xr-x bitnami ]  ./.git/info
[-rw-r--r-- bitnami ]  ./.git/info/exclude
[drwxr-xr-x bitnami ]  ./.git/logs
[-rw-r--r-- bitnami ]  ./.git/logs/HEAD
[drwxr-xr-x bitnami ]  ./.git/logs/refs
[drwxr-xr-x bitnami ]  ./.git/logs/refs/heads
[-rw-r--r-- bitnami ]  ./.git/logs/refs/heads/main
[drwxr-xr-x bitnami ]  ./.git/logs/refs/remotes
[drwxr-xr-x bitnami ]  ./.git/logs/refs/remotes/origin
[-rw-r--r-- bitnami ]  ./.git/logs/refs/remotes/origin/HEAD
[drwxr-xr-x bitnami ]  ./.git/objects
[drwxr-xr-x bitnami ]  ./.git/objects/info
[drwxr-xr-x bitnami ]  ./.git/objects/pack
[-r--r--r-- bitnami ]  ./.git/objects/pack/pack-fe97cda37bd06564a475f5cf7cd04af752b1cdb1.idx
[-r--r--r-- bitnami ]  ./.git/objects/pack/pack-fe97cda37bd06564a475f5cf7cd04af752b1cdb1.pack
[-rw-r--r-- bitnami ]  ./.git/packed-refs
[drwxr-xr-x bitnami ]  ./.git/refs
[drwxr-xr-x bitnami ]  ./.git/refs/heads
[-rw-r--r-- bitnami ]  ./.git/refs/heads/main
[drwxr-xr-x bitnami ]  ./.git/refs/remotes
[drwxr-xr-x bitnami ]  ./.git/refs/remotes/origin
[-rw-r--r-- bitnami ]  ./.git/refs/remotes/origin/HEAD
[drwxr-xr-x bitnami ]  ./.git/refs/tags
[drwxr-xr-x bitnami ]  ./.github
[drwxr-xr-x bitnami ]  ./.github/workflows
[-rw-r--r-- bitnami ]  ./.github/workflows/codeql-analysis.yml
[-rw-r--r-- bitnami ]  ./init.rb
[drwxr-xr-x bitnami ]  ./lib
[drwxr-xr-x bitnami ]  ./lib/redmine_more_previews
[drwxr-xr-x bitnami ]  ./lib/redmine_more_previews/hooks
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews/hooks/icon_css.rb
[drwxr-xr-x bitnami ]  ./lib/redmine_more_previews/lib
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews/lib/controller_helper.rb
[drwxr-xr-x bitnami ]  ./lib/redmine_more_previews/lib/conversion
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews/lib/conversion/convert.html.erb
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews/lib/conversion/convert.pango.erb
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews/lib/conversion/convert.pdf.erb
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews/lib/conversion/convert.txt.erb
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews/lib/conversion/emoji1.png
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews/lib/conversion/emoji2.png
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews/lib/conversion/emoji3.png
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews/lib/conversion/emoji4.png
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews/lib/conversion/emoji5.png
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews/lib/conversion.rb
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews/lib/converter.rb
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews/lib/exceptions.rb
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews/lib/rmp_file.rb
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews/lib/rmp_img.rb
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews/lib/rmp_meta.rb
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews/lib/rmp_pdf.rb
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews/lib/rmp_shell.rb
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews/lib/rmp_text.rb
[drwxr-xr-x bitnami ]  ./lib/redmine_more_previews/patches
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews/patches/admin_controller_patch.rb
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews/patches/application_helper_patch.rb
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews/patches/attachment_patch.rb
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews/patches/attachments_controller_patch.rb
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews/patches/entry_patch.rb
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews/patches/mime_type_patch.rb
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews/patches/repositories_controller_patch.rb
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews/patches/repository_patch.rb
[-rw-r--r-- bitnami ]  ./lib/redmine_more_previews.rb
[-rw-r--r-- bitnami ]  ./LICENSE
[-rw-r--r-- bitnami ]  ./README.md

91 directories, 154 files

**Comment by HugoHasenbein** [comment]
then in the rails console type:

2.7.2:> RedmineMorePreviews::Converter.load

it should respond with

2.7.2> ["/opt/redmine-4.1.0/plugins/redmine_more_previews/converters/cliff", "/opt/redmine-4.1.0/plugins/redmine_more_previews/converters/libre", "/opt/redmine-4.1.0/plugins/redmine_more_previews/converters/mark", "/opt/redmine-4.1.0/plugins/redmine_more_previews/converters/nil_text", "/opt/redmine-4.1.0/plugins/redmine_more_previews/converters/peek", "/opt/redmine-4.1.0/plugins/redmine_more_previews/converters/zippy"]

**Comment by kyvaith** [comment]
Hello and happy new year!

Loading production environment (Rails 5.2.6)
irb(main):001:0> RedmineMorePreviews::Converter.load
=> ["/opt/bitnami/redmine/plugins/redmine_more_previews/converters/cliff", "/opt/bitnami/redmine/plugins/redmine_more_previews/converters/libre", "/opt/bitnami/redmine/plugins/redmine_more_previews/converters/mark", "/opt/bitnami/redmine/plugins/redmine_more_previews/converters/nil_text", "/opt/bitnami/redmine/plugins/redmine_more_previews/converters/peek", "/opt/bitnami/redmine/plugins/redmine_more_previews/converters/zippy"]
irb(main):002:0>

**Comment by kyvaith** [comment]
Hi, @HugoHasenbein do you have any clue?

**Comment by HugoHasenbein** [comment]
To be honest: no, I have no idea, because I cannot look into your installation of redmine

You wrote, that RedmineMorePreviews::Converter.registered_converters reveals an empty array, but RedmineMorePreviews::Converter.load returns the paths of the loaded converters. It seems, your redmine installation fails silently in the process of registering the plugins.

Sorry

Stephan

**Comment by HugoHasenbein** [comment]
Dear Thomas,

working on a different project I came across an issue with bitnami.

Try to add the following line to

/redmine_more_previews/lib/redmine_more_previews/converter.rb:

original:

358    def self.configured_converters
359      begin
360        ::Setting['plugin_redmine_more_previews'].to_h rescue {}
361      end["converter"].to_h
362    end #def


add:

358    def self.configured_converters
359      begin
360        ::Setting.check_cache
361        ::Setting['plugin_redmine_more_previews'].to_h rescue {}
362      end["converter"].to_h
363    end #def

This may remedy the problem. I suspect, bitnami has fully independent threads, so that caches are not updated.

Please give feedback, if that remedied the situation

best regards

Stephan

**Comment by kyvaith** [comment]
So I've added a line ::Setting.check_cache

in file /bitnami/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/lib/converter.rb

Migrated plugins and restarted server. Didn't helped. Still have empty plugins section.

**Comment by HugoHasenbein** [comment]
If you have access to the database, then try to get from table "settings" the one with "name" = 'plugin_redmine_more_previews'. From that row send the "value", which is likely something like:

--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
embedding: '1'
converter: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  cliff: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    active: '1'
    mime_types: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      eml: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        active: '1'
        format: html
      mime: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
  libre: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    active: '1'
    mime_types: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      csv: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      doc: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      docm: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      docx: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        active: '1'
        format: html
      dotm: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      dotx: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      fodg: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      fodp: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      fods: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      fodt: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      odb: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      odc: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      odf: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      odg: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      odi: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      odm: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      odp: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      ods: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      odt: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        active: '1'
        format: pdf
      otg: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      oth: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      otp: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      ots: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      ott: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      oxt: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      potm: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      potx: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      ppt: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      pptm: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      pptx: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      rtf: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      sda: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      sdc: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      sdd: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      sdp: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      sds: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      sdw: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      sgl: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      smf: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      stc: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      std: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      sti: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      stw: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      sxc: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      sxd: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      sxg: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      sxi: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      sxm: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      sxw: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      vor: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      xls: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        active: '1'
        format: pdf
      xlsm: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      xlsx: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        active: '1'
        format: html
      xltm: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      xltx: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
  mark: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    active: '1'
    mime_types: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      md: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        active: '1'
        format: html
      textile: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      html: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
  nil_text: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    active: '1'
    example: '12345678'
    mime_types: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      txt: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        active: '1'
        format: inline
  peek: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    active: '1'
    mime_types: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      pdf: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        active: '1'
        format: pdf
  zippy: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    active: '1'
    mime_types: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      zip: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        active: '1'
        format: html
      tar: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html
      tgz: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        format: html

**Comment by kyvaith** [comment]
MariaDB [bitnami_redmine]> select * from settings where name like 'plugin_redmine_more_previews';
+----+------------------------------+----------------------------------------------------------------------------------------------------------------------+---------------------+
| id | name                         | value                                                                                                                | updated_on          |
+----+------------------------------+----------------------------------------------------------------------------------------------------------------------+---------------------+
| 97 | plugin_redmine_more_previews | --- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
embedding: '0'
absolute: '1'
cache_previews: '1'
debug: '1'
 | 2022-01-26 12:48:50 |
+----+------------------------------+----------------------------------------------------------------------------------------------------------------------+---------------------+
1 row in set (0.001 sec)

**Comment by kyvaith** [comment]
So maybe some DB migrations are missing?

**Comment by kyvaith** [comment]
I moved whole plugins folder according to issue #26 and it works. But I have a lot of plugins and only this one requires this change, so I suggest to future investigate the problem. For me it's enough.
