### ISSUE TITLE
Doesn't work at Redmine 4.0.5

### ISSUE THREAD

**Issue by Yarrax** [HugoHasenbein/redmine_more_previews#4]
Hi. I use redmine 4.0.5.
OS: Centos 7
Ruby: installed via RVM:
ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]

<del>I ve hot 2 errors: </del>

<del>1. when i go to Administration ->  Plugins -> Redmine More Previews Configuration i've got 404 error.
2. in system I install libreoffice 6.4.7. When i click on odt document I've got 
`Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.
If you are the Redmine administrator, check your log files for details about the error.`</del>

**UPD.** Sorry. It's my mistake. I when i rename directory to redmine_more_previews (from "redmine_more_previews_main") 0 all work.

**UPD.2** How many pages from odt must view plugin? I see only 2 pages if i use html-view. Doc and odt work correct in pdf-view mode, but xls and ods view at portrait mode (it's not good).

**Comment by HugoHasenbein** [comment]
Dear Yarrax,

can you tell me, which other plugins you have installed? Redmine More previews should run without migration. Just copy the plugin and restart Redmine.

Are you using the latest version of Redmine More Previews 2.0.1?

Best regards

Stephan

**Comment by Yarrax** [comment]
Dear Stephan, 
thanks fro your answer.


I use plugins:

a_common_libs  
custom_menu 
 redmine_more_previews  
rgloader  
usability

Right now plugin work good, if i set pdf-view for doc and odt formats.
If i try to set html preview, it will open only 1-2 pages from documents. all other - skipped.

I am forced to use html previews for tables, since in pdf previews they break tables to fit in A4 format.

Best regard, Alex.
