### ISSUE TITLE
plugin not kicking in

### ISSUE THREAD

**Issue by madmoe00** [HugoHasenbein/redmine_more_previews#78]
Hello,
I have installed and enabled this plugin on redmine 5.0.5 yet it is not previewing. here is the information on redmine:
I have also installed LibreOffice OS is Ubuntu 22.04

System:
![image](https://github.com/HugoHasenbein/redmine_more_previews/assets/3762174/e97689d4-acec-4472-9ca8-7193dd8a21c1)

Plugins:
![image](https://github.com/HugoHasenbein/redmine_more_previews/assets/3762174/1b592f5a-ffb8-460b-8e80-8eb568adb329)

Task preview
![image](https://github.com/HugoHasenbein/redmine_more_previews/assets/3762174/e7682425-cfc3-4c72-be79-3009027d88be)

Thanks!

**Comment by keineahnung2345** [comment]
You need to enable it in your project setting.

**Comment by madmoe00** [comment]
OMG!!! Thanks Greatest app on redmine!
