### ISSUE TITLE
libreoffice not available

### ISSUE THREAD

**Issue by scottenberg** [HugoHasenbein/redmine_more_previews#8]
Hi, I've installed the plugin on my Bitnami redmine version 4.1.1 on Debian distribution.
I've installed libreoffice version 6.1.5.2 10(Build:2), but it results as not available as you can see in the attached image
![immagine](https://user-images.githubusercontent.com/78471569/106720026-44caab80-6603-11eb-8329-2ce48a8bfa92.png)

I noticed that error on the log of apache 
App 22373 output: /usr/lib/libreoffice/program/soffice.bin: /opt/bitnami/common/lib/libldap_r-2.4.so.2: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4)
App 22373 output: /usr/lib/libreoffice/program/soffice.bin: /opt/bitnami/common/lib/liblber-2.4.so.2: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4)
App 22373 output: /usr/lib/libreoffice/program/soffice.bin: /opt/bitnami/common/lib/libuuid.so.1: no version information available (required by /usr/lib/x86_64-linux-gnu/libSM.so.6)
App 22373 output: /usr/lib/libreoffice/program/soffice.bin: /opt/bitnami/common/lib/libuuid.so.1: no version information available (required by /lib/x86_64-linux-gnu/libblkid.so.1)
App 22373 output: /usr/lib/libreoffice/program/soffice.bin: symbol lookup error: /usr/lib/x86_64-linux-gnu/libcairo.so.2: undefined symbol: FT_Get_Var_Design_Coordinates

**Comment by HugoHasenbein** [comment]
Dear Scottenberg,

maybe there is an install problem with Libre Office? The errors seem to relate to Libre Office...

**Comment by scottenberg** [comment]
Thank you for your reply, I tried to unistall and reinstall libreoffice, and no errors or warning happened during the installation.
There is a suggested version of libreoffice?
