### ISSUE TITLE
More_previews does not work on redmine 5.0.1 stable

### ISSUE THREAD

**Issue by chalchal18** [HugoHasenbein/redmine_more_previews#80]
Hello @HugoHasenbein ,
Redmine more previews does not work on ubuntu. I use Redmine 5.0.1. stable and Rails version is 6.1.6 . Even though I cloned redmine_more_previews to my system, it does not work. Could you please help me to get a solution.I have attached the log file and some screenshot for your reference .
preview
information
log_ss

![information](https://github.com/HugoHasenbein/redmine_more_previews/assets/129147918/abc25627-e5fc-4dcf-a873-9a411ec04974)
![log_ss](https://github.com/HugoHasenbein/redmine_more_previews/assets/129147918/4c0de878-cc0d-4944-817e-f89a4802b546)
![preview](https://github.com/HugoHasenbein/redmine_more_previews/assets/129147918/9089f757-7312-421a-a051-5e8e70f0a066)

**Comment by andymilga** [comment]
redmine 5.0.5 same
![image](https://github.com/HugoHasenbein/redmine_more_previews/assets/5157249/e0a9973b-a82b-4e24-9e56-733701e221b9)

**Comment by HugoHasenbein** [comment]
did you activate the plugin in the project configuration for the project?

**Comment by chalchal18** [comment]
Yes,I activated,but it does not work .

**Comment by andymilga** [comment]
> did you activate the plugin in the project configuration for the project?
> […](#)

@HugoHasenbein sorry, no.
set on and all works fine. thanks

should add this in readme?

**Comment by chalchal18** [comment]
Even though I apply Libre but does not work.I have attached some photos for you to look over.
![image](https://github.com/HugoHasenbein/redmine_more_previews/assets/129147918/18f42a75-b4dd-4c4d-9cb2-75f58f6ccfca)
![image](https://github.com/HugoHasenbein/redmine_more_previews/assets/129147918/7efaecd4-80b9-46b1-aa09-25dff646d328)
![image](https://github.com/HugoHasenbein/redmine_more_previews/assets/129147918/ce70459c-cca0-4953-9385-5f2e72c99d5e)

Thanks in advance.

**Comment by vokamut** [comment]
Activate the plugin in the project

![2023-06-16_14-13](https://github.com/HugoHasenbein/redmine_more_previews/assets/4266448/cb4c5857-1321-469f-b895-93a26718b858)

**Comment by chalchal18** [comment]
Thanks for your reply @vokamut 
Yes, I already activated this plugin in the project and it works well.
But I have one issue and could you help me to get an answer?
This preview plugin works with a lot of extensions except .pdf. In the pdf extension, show to download instead of preview.

**Comment by HugoHasenbein** [comment]
can you provide a screenshot of the plugin configuration page where you chose the extensions?

**Comment by HugoHasenbein** [comment]
looks good, anything in the log file?

**Comment by chalchal18** [comment]
I didn't see any error log file.

**Comment by HugoHasenbein** [comment]
enable caching in plugin configuration. Then go to the files directory in your redmine root directory after you have tried to see the preview. In the files subdirectory there should be a path to the pdf file

**Comment by chalchal18** [comment]
Finally, it works well.
Really appreciate your support.
