### ISSUE TITLE
Install on Redmine 5.0.1

### ISSUE THREAD

**Issue by jannikk09** [HugoHasenbein/redmine_more_previews#88]
Hey i get this issue: 
![image](https://github.com/HugoHasenbein/redmine_more_previews/assets/93577959/82d31840-cef1-4106-bf5f-dddfb062c0dc)

In the console i get "rake aborted!" after this command: 
 bundle exec rake redmine:plugins NAME=redmine_more_previews RAILS_ENV=production

Maybe I need an older version of the plugin?

**Comment by HugoHasenbein** [comment]
bundle exec rake redmine:plugins:migrate NAME=redmine_more_previews RAILS_ENV=production

**Comment by jannikk09** [comment]
I still get this issue: 
![image](https://github.com/HugoHasenbein/redmine_more_previews/assets/93577959/57b6c8e9-a768-43e6-839d-97156b0786cc)

**Comment by jannikk09** [comment]
After removing Redmine X Lightbox it seems to be working. Thank you
